
let token=localStorage.getItem("wfn_token"), me=null;
const $=id=>document.getElementById(id);
async function api(url,opt={}) {
  opt.headers={...(opt.headers||{}),"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})};
  const r=await fetch(url,opt); const d=await r.json().catch(()=>({}));
  if(!r.ok) throw Error(d.error||"Request failed"); return d;
}
function toast(msg){$("toast").textContent=msg;$("toast").className="show";setTimeout(()=>$("toast").className="",2400)}
function showPanel(){ $("auth").classList.add("hidden");$("panel").classList.remove("hidden");$("logout").classList.remove("hidden"); $("who").textContent=me.username+" • "+me.role.toUpperCase(); document.querySelectorAll("#usersNav,#settingsNav,.ownerOnly").forEach(x=>x.classList.toggle("hidden",x.id==="usersNav"? !["owner","admin"].includes(me.role):x.id==="settingsNav"||x.classList.contains("ownerOnly")?me.role!=="owner":false)); loadAll();}
async function loadAll(){me=await api("/api/me");$("who").textContent=me.username+" • "+me.role.toUpperCase();const s=await api("/api/dashboard");$("stUsers").textContent=s.users;$("stLicenses").textContent=s.licenses;$("stActive").textContent=s.active;$("stBalance").textContent="₹"+Number(me.balance).toFixed(2);$("accountInfo").innerHTML=`<p><b>${me.username}</b></p><p class="muted">Role: ${me.role}</p><p class="muted">Referral: ${me.referral_code}</p>`;loadLicenses();loadRefs();if(["owner","admin"].includes(me.role))loadUsers();if(me.role==="owner")loadSettings();}
function go(page){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(page).classList.remove("hidden");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===page));$("pageTitle").textContent=page[0].toUpperCase()+page.slice(1);if(page==="users"&&["owner","admin"].includes(me.role))loadUsers();if(page==="licenses")loadLicenses();if(page==="referrals")loadRefs();}
document.addEventListener("click",e=>{const b=e.target.closest("[data-page]");if(b)go(b.dataset.page)});
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("loginBox").classList.toggle("hidden",b.dataset.tab!=="login");$("registerBox").classList.toggle("hidden",b.dataset.tab!=="register")});
$("loginBtn").onclick=async()=>{try{const d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({username:$("loginUser").value,password:$("loginPass").value})});token=d.token;localStorage.setItem("wfn_token",token);me=d.user;showPanel()}catch(e){toast(e.message)}};
$("regBtn").onclick=async()=>{try{await api("/api/auth/register",{method:"POST",body:JSON.stringify({username:$("regUser").value,password:$("regPass").value,referral:$("regRef").value})});toast("Account created. Login now.");document.querySelector('[data-tab="login"]').click()}catch(e){toast(e.message)}};
$("logout").onclick=()=>{localStorage.removeItem("wfn_token");location.reload()};
async function loadLicenses(){if(!token)return;try{const ls=await api("/api/licenses");$("licenseRows").innerHTML=ls.map(l=>`<tr><td><b>${l.license_key}</b></td><td>${l.license_type}</td><td>₹${Number(l.price).toFixed(2)}</td><td class="${l.status}">${l.status}</td><td>${l.device_id||"Unbound"}</td><td>${new Date(l.expires_at).toLocaleString()}</td><td><button onclick="extendKey(${l.id})">+30d</button> <button onclick="resetDevice(${l.id})">Reset</button> <button onclick="deleteKey(${l.id})">Delete</button></td></tr>`).join("")}catch(e){toast(e.message)}}
window.extendKey=async id=>{try{await api("/api/licenses/"+id+"/extend",{method:"POST",body:JSON.stringify({days:30})});loadLicenses();toast("License extended")}catch(e){toast(e.message)}};
window.resetDevice=async id=>{try{await api("/api/licenses/"+id+"/reset-device",{method:"POST"});loadLicenses();toast("Device reset")}catch(e){toast(e.message)}};
window.deleteKey=async id=>{if(!confirm("Delete this key?"))return;try{await api("/api/licenses/"+id,{method:"DELETE"});loadLicenses();toast("Key deleted")}catch(e){toast(e.message)}};
$("refreshLicenses").onclick=loadLicenses;
$("generateBtn").onclick=async()=>{try{const d=await api("/api/licenses/generate",{method:"POST",body:JSON.stringify({custom:$("customKey").value,count:$("keyCount").value,days:$("keyDays").value,license_type:$("keyType").value,price:$("keyPrice").value})});$("generated").textContent=d.licenses.map(x=>x.license_key).join("\n");$("customKey").value="";loadLicenses();toast(d.licenses.length+" key(s) generated")}catch(e){toast(e.message)}};
$("extendAll").onclick=async()=>{try{const d=await api("/api/licenses/extend-all",{method:"POST",body:JSON.stringify({days:$("extendAllDays").value})});loadLicenses();toast("Extended "+d.count+" keys")}catch(e){toast(e.message)}};
$("resetAll").onclick=async()=>{if(!confirm("Reset all device bindings?"))return;try{await api("/api/licenses/reset-all",{method:"POST"});loadLicenses();toast("All devices reset")}catch(e){toast(e.message)}};
$("deleteAll").onclick=async()=>{if(!confirm("Delete ALL keys permanently?"))return;try{await api("/api/licenses/all",{method:"DELETE"});loadLicenses();toast("All keys deleted")}catch(e){toast(e.message)}};
async function loadUsers(){try{const us=await api("/api/users");$("userRows").innerHTML=us.map(u=>`<tr><td>${u.username} <small>#${u.id}</small></td><td>${u.role}</td><td>₹${Number(u.balance).toFixed(2)}</td><td>${u.referral_code}</td><td><button onclick="changeRole(${u.id},'admin')">Admin</button> <button onclick="changeRole(${u.id},'reseller')">Reseller</button> <button onclick="deleteUser(${u.id})" class="danger">Delete</button></td></tr>`).join("")}catch(e){toast(e.message)}}
window.changeRole=async(id,role)=>{try{await api("/api/users/"+id+"/role",{method:"POST",body:JSON.stringify({role})});loadUsers();toast("Role updated")}catch(e){toast(e.message)}};
window.deleteUser=async id=>{if(!confirm("Delete this user?"))return;try{await api("/api/users/"+id,{method:"DELETE"});loadUsers();toast("User deleted")}catch(e){toast(e.message)}};
$("refreshUsers").onclick=loadUsers;
$("balBtn").onclick=async()=>{try{await api("/api/users/"+$("balUser").value+"/balance",{method:"POST",body:JSON.stringify({amount:$("balAmount").value,note:$("balNote").value})});toast("Balance updated");loadUsers()}catch(e){toast(e.message)}};
async function loadRefs(){try{const d=await api("/api/referrals");$("refCode").textContent=d.code;$("refReward").textContent="₹"+d.reward;$("refRows").innerHTML=d.items.map(x=>`<tr><td>${x.referred_username}</td><td>₹${x.reward}</td><td>${new Date(x.created_at).toLocaleString()}</td></tr>`).join("")}catch(e){toast(e.message)}}
$("usernameBtn").onclick=async()=>{try{await api("/api/profile/username",{method:"POST",body:JSON.stringify({username:$("newUsername").value})});toast("Username changed");loadAll()}catch(e){toast(e.message)}};
$("passwordBtn").onclick=async()=>{try{await api("/api/profile/password",{method:"POST",body:JSON.stringify({password:$("newPassword").value})});toast("Password changed")}catch(e){toast(e.message)}};
async function loadSettings(){try{const s=await api("/api/settings");$("setPanel").value=s.panel_name;$("setLicense").value=s.license_name;$("setPrice").value=s.license_price;$("setReward").value=s.referral_reward}catch(e){toast(e.message)}}
$("saveSettings").onclick=async()=>{try{await api("/api/settings",{method:"POST",body:JSON.stringify({panel_name:$("setPanel").value,license_name:$("setLicense").value,license_price:$("setPrice").value,referral_reward:$("setReward").value})});toast("Settings saved")}catch(e){toast(e.message)}};
if(token)api("/api/me").then(u=>{me=u;showPanel()}).catch(()=>{localStorage.removeItem("wfn_token");token=null});
